spark-submit --master "local[*]" task.py
spark-submit --master "local[*]" task_2.py
spark-submit --master "local[*]" task.py
spark-submit --master "local[*]" task_1.py
spark-submit --master "local[*]" task_1(2).py
spark-submit --master "local[*]" task_1.py
spark-submit --master "local[*]" task_1_2.py
spark-submit --master "local[*]" task_2_balance.py
spark-submit --master "local[*]" task_2_turnover.py
spark-submit --master "local[*]" task_2_balance.py
spark-submit --master "local[*]" task_2_turnover.py
spark-submit --master "local[*]" test_turnover.py
spark-submit --master "local[*]" task_3.py
spark-submit --master "local[*]" task_1_2.py
spark-submit --master "local[*]" task_1.py
spark-submit --master "local[*]" task_1_2.py
spark-submit --master "local[*]" test_turnover.py
spark-submit --master "local[*]" task_2_turnover.py
spark-submit --master "local[*]" task_1.py
